config/routes.rb
Rails.application.routes.draw do
  ActiveAdmin.routes(self)
  scope '(:locale)', locale: /en|pt-BR/ do
    devise_for :users, controllers: { confirmations: 'users/confirmations' }
    # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
    resources :profiles, except: [:index]
    resources :contents, only: [:new, :create, :show]
    resources :contests, only: [:show, :index]

    scope format: true, constraints: { format: :json } do
      get '/contents', to: 'contents#index', as: :all_contents
      put '/contents/:id/evaluation', to: 'contents#evaluation', as: :content_evaluation
      get '/videos', to: 'contents#index'
      get '/videos/:id', to: 'contents#video', as: :get_video
      get '/contents/:id/related', to: 'contents#related_contents', as: :related_contents
    end

    scope :contents do
      post '/zencoder_callback', to: 'contents#zencoder_callback', as: :content_zencoder_callback
      get '/:id/map_view', to: 'contents#map_view', as: :map_view
      get '/:id/map_player', to: 'contents#map_player', as: :map_player
      get '/:id/share_button', to: 'contents#share_button', as: :share_button
      get '/:id/share_box', to: 'contents#share_box', as: :share_box
    end

    post '/public_rating', to: 'public_ratings#public_rating', as: :public_rating

    get 'states' => 'profiles#states', as: 'states'

    # static views' routes
    get 'terms_of_use' => 'static_views#terms_of_use', as: 'terms_of_use'
    get 'creative_commons' => 'static_views#creative_commons', as: 'creative_commons'
    get 'sponsorship' => 'static_views#sponsorship', as: 'sponsorship'
    get 'contact_us' => 'static_views#contact_us', as: 'contact_us'
    get 'soundtrack_copyright' => 'static_views#soundtrack_copyright', as: 'soundtrack_copyright'
    get 'faq' => 'static_views#faq', as: 'faq'
    get 'education' => 'static_views#education', as: 'education'
    get 'exhibit_on_your_institution' => 'static_views#exhibit_on_your_institution', as: 'exhibit_on_your_institution'
    get 'about_us' => 'static_views#about_us', as: 'about_us'
    get 'image_copyright' => 'static_views#image_copyright', as: 'image_copyright'
    get 'exhibition_network' => 'static_views#exhibition_network', as: 'exhibition_network'

    root to: 'home#index'
  end
end

app/models/content.rb
require 'validators/content_user_profile_validator'
require 'validators/content_contest_validator'

class Content < ApplicationRecord
  RELATED_CONTENTS_LIST_SIZE = 30

  validates :terms_of_service, acceptance: true

  validates :title, :user_id, :soundtrack, :director, presence: true
  validates_with ContentUserProfileValidator, unless: 'user_id.nil?'
  validates_with ContentContestValidator, unless: 'contests.blank?', on: :create

  after_create :send_to_zencoder
  after_create -> { JudgeEvaluation.create!(content: self) }
  after_save :update_coordinates, if: :zip_code_changed?

  has_many :encoded_contents
  has_many :public_ratings
  has_and_belongs_to_many :contests
  has_and_belongs_to_many :playlists
  has_one :coordinate
  has_one :judge_evaluation
  has_many :thumbnails, through: :encoded_contents
  has_many :original_medias

  belongs_to :user

  # The default_scope is applied across all queries to the model.
  # It is also applied while creating/building a record. It is not applied while updating a record. That means that Content.new will return an object with attribute 'deleted' assigned false.
  default_scope { where(deleted: false) }
  scope :finished, -> { includes(:encoded_contents).where(encoded_contents: { state: 'finished' }) }
  scope :unfinished, -> { includes(:encoded_contents).where(encoded_contents: { state: nil }).or(includes(:encoded_contents).where.not(encoded_contents: { state: 'finished' })) }
  scope :evaluated, -> { includes(:judge_evaluation).where(judge_evaluations: {evaluation_state: 'evaluated'}) }
  scope :not_evaluated, -> { includes(:judge_evaluation).where.not(judge_evaluations: {evaluation_state: 'evaluated'}) }
  scope :with_found_coordinates, -> { includes(:coordinate).where(coordinates: { found: true }) }
  scope :featured, -> { joins(:judge_evaluation).where('judge_evaluations.judge_rating >= ?', JudgeEvaluation::FEATURED_THRESHOLD) }
  scope :show_on_map, -> { finished.with_found_coordinates }
  scope :recent, -> { finished.evaluated.order(created_at: :desc) }

  accepts_nested_attributes_for :original_medias

  def view_counter_attribute
    'view_count'
  end

  include CoordinateSearcher
  include SupportForViewCounting

  delegate :evaluation_state, to: :judge_evaluation
  delegate :label_evaluated, to: :judge_evaluation
  delegate :label_corrupted, to: :judge_evaluation
  delegate :label_piracy, to: :judge_evaluation
  delegate :label_repeated, to: :judge_evaluation
  delegate :rollback_bad_state, to: :judge_evaluation
  delegate :bad_state?, to: :judge_evaluation
  delegate :featured?, to: :judge_evaluation
  delegate :evaluated?, to: :judge_evaluation
  delegate :judge_rating, to: :judge_evaluation

  def average_grade
    public_ratings.average(:grade)
  end

  def finished_encoded_contents
    encoded_contents.where(state: :finished)
  end

  def finished_encoded_contents?
    !finished_encoded_contents.empty?
  end

  def send_to_evaluation
    EvaluationSystem.request_evaluation(self)
    judge_evaluation.send_to_evaluation
  end

  def description
    nil
  end

  # FIXME: What about putting this one on the helper and adding hooks after some transactions? Would be update_coordinates(content)
  def update_coordinates
    if self.zip_code.nil?
      address = self.user.city
      type = :city
    else
      address = self.zip_code
      type = :zip_code
    end
    geolocation = search_coordinates(address, type)
    attributes = { latitude: geolocation[:lat], longitude: geolocation[:lng], found: !geolocation.empty?, content: self }
    if self.coordinate.nil?
      Coordinate.create(attributes)
    else
      self.coordinate.update(attributes)
    end
  end

  def related_contents
    Rails.cache.fetch("#{cache_key}/related_contents", expires_in: 10.hours) do
      contents_in_same_contests = Content.joins(:contents_contests).where('contents_contests.contest_id' => self.contests.pluck(:id)).where.not(id: self.id).distinct
      related_contents_list = contents_in_same_contests.featured
      related_contents_list = fill_with_additional_featured_contents(related_contents_list) if related_contents_list.size < RELATED_CONTENTS_LIST_SIZE
      related_contents_list.shuffle
    end
  end

  def fill_with_additional_featured_contents(related_contents_list)
    already_inserted_ids = (related_contents_list.pluck(:id) << self.id)
    related_contents_list + Content.where.not(id: already_inserted_ids).featured.sample(RELATED_CONTENTS_LIST_SIZE - related_contents_list.size)
  end

  def self.contents_for_map_with_logged_in_user(user)
    user_contents = user_finished_contents(user)
    user_contents + generic_contents_for_map(user.adult?)
  end

  def self.generic_contents_for_map(adult = false)
    Set.new(show_on_map.featured.evaluated.where(adult: adult))
  end

  def self.user_finished_contents(user)
    Set.new(show_on_map.where(user: user))
  end

  private

  def send_to_zencoder
    RequestZencoderJob.perform_later(self)
  end
end

app/controllers/contents_controller.rb
# FIXME: https://gitlab.com/minuto/media_choice/issues/99
# rubocop:disable Metrics/ClassLength
class ContentsController < ApplicationController
  before_action :set_content, only: [:show, :evaluation, :video, :map_view, :related_contents, :map_player, :share_button, :share_box]
  before_action :check_evaluated_content, only: [:show]
  before_action :find_last_encoded_video, only: [:show, :map_player]
  before_action :authenticate_user!, only: [:new, :create]
  before_action :check_profile, only: [:new, :create]
  before_action :find_contests, only: [:create]
  protect_from_forgery with: :null_session, only: :zencoder_callback

  respond_to :json, only: [:index, :video, :evaluation, :related_contents]

  # FIXME: https://gitlab.com/minuto/media_choice/issues/98
  # rubocop:disable Metrics/AbcSize
  # GET /contents.json
  def index
    contents = []
    status = :bad_request

    if params.key? :ids
      ids = params[:ids].split(',')
      contents = Content.where(id: ids)
      status = contents.count == ids.count ? :ok : :partial_content
    elsif params.key?(:user_id) && params.key?(:orig_id)
      contents = Content.where(user_id: params[:user_id], id: params[:orig_id])
      status = :ok
    end

    render json: contents.map { |content| EvaluationSystem.content_json_for_evaluation(content) }, status: status
  end
  # rubocop:enable Metrics/AbcSize

  def video
    render json: EvaluationSystem.content_json_for_evaluation(@content)
  end

  def evaluation
    evaluation_state = params[:content]['evaluation_state']
    if evaluation_state == 'evaluated'
      if @content.bad_state?
        @content.rollback_bad_state
      end
      @content.judge_evaluation.update(judge_rating: params[:content][:rating])
      @content.label_evaluated
    else
      transition = "label_#{evaluation_state}".to_sym
      @content.send(transition) if @content.respond_to? transition
    end
  end

  # GET /contents/1
  # GET /contents/1.json
  def show
    @video = @encoded_video.video
    ViewCounter.create!(viewed_model: Content.to_s, model_id: @content.id)
  end

  # GET /contents/new
  def new
    @content = Content.new
    @content.original_medias.build
    @contests = Contest.started
  end

  # POST /contents
  # POST /contents.json
  def create
    @content = Content.new(content_params)
    @content.user_id = current_user.id
    @content.contests = @contests

    respond_to do |format|
      if @content.save
        format.html { redirect_to root_path, notice: I18n.t('successfully_created_video') }
      else
        format.html { render :new }
      end
    end
  end

  def zencoder_callback
    @encoded_content = EncodedContent.find_by(job_id: params[:job][:id])
    unless @encoded_content.nil?
      update_encoded_content @encoded_content, params[:outputs].first
      @encoded_content.content.send_to_evaluation
    end

    head :no_content
  end

  def map_view
    if @content.coordinate&.found
      if user_signed_in?
        @contents = Content.contents_for_map_with_logged_in_user(current_user) + [@content]
      else
        @contents = Content.generic_contents_for_map + [@content]
      end
    else
      redirect_to content_path(@content.id), notice: I18n.t('not_found_on_map')
    end
  end

  def related_contents
    related = @content.related_contents
    render json: build_related_videos_json(related), status: :ok
  end

  def map_player
    render partial: 'map_player'
  end

  def share_button
    render partial: 'share_button', locals: { id: @content.id }
  end

  def share_box
    render partial: 'share_box', locals: { content: @content }
  end

  private

  def update_encoded_content(encoded_content, parameters)
    encoded_content.output_id = parameters[:id]
    encoded_content.state = parameters[:state]
    encoded_content.width = parameters[:width]
    encoded_content.height = parameters[:height]
    encoded_content.duration = parameters[:duration_in_ms]
    encoded_content.file_size = parameters[:file_size_in_bytes]
    encoded_content.video = URI.parse(parameters[:url])
    if encoded_content.save
      Thumbnail.create!(
        image: URI.parse(parameters[:thumbnails].first[:images].first[:url]),
        encoded_content: encoded_content
      )
    end
  end

  # Use callbacks to share common setup or constraints between actions.
  def set_content
    @content = Content.find(params[:id])
  end

  def check_evaluated_content
    redirect_back(fallback_location: root_path, flash: { warning: I18n.t('content_not_yet_evaluated') }) unless @content.evaluated?
  end

  def check_profile
    redirect_to(new_profile_path, flash: { warning: I18n.t('need_complete_profile_to_send_content') }) if current_user.profile.nil?
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def content_params
    params.require(:content).permit(:title, :user_id, :adult, :soundtrack, :view_count, :deleted, :zip_code, :director, :co_director, :team, :allow_comments, original_medias_attributes: [:media])
  end

  def find_last_encoded_video
    redirect_to(root_path, flash: { warning: I18n.t('video_has_not_finished_encoding') }) && return unless @content.finished_encoded_contents?
    @encoded_video = @content.encoded_contents.last
  end

  def find_contests
    params.require(:contests)
    @contests = Contest.find(params[:contests])
  rescue ActiveRecord::RecordNotFound, ActionController::ParameterMissing => error
    redirect_to new_content_path, alert: I18n.t('contest_not_found')
    logger.debug error
  end

  def build_related_videos_json(related_list)
    related_list.map do |content|
      {
        # The title and full_name must have a limit of characters. Otherwise, it breaks the related contents CSS
        title: content.title.truncate(18),
        url: content_path(content.id),
        image: content.thumbnails.last.url,
        author: content.user.profile.full_name.truncate(22)
      }
    end
  end
end
# rubocop:enable Metrics/ClassLength

app/helpers/contents_helper.rb
module ContentsHelper
  def contest_list_for(content)
    contents_contests = content.contests
    if contents_contests.empty?
      I18n.t('contents.content_details.none')
    else
      contest_list = contents_contests.map { |contest| link_to(contest.name, contest_path(id: contest.id)) }
      safe_join(contest_list)
    end
  end
end

app/views/contents/_content_details.html.erb
<div class="content-details">
  <div class="left-col">
    <h2 class="content-title"><%= content.title %></h2>
    <div class="inline-grid">
      <h3 class="content-author"><%= t('.by') %> <%= content.user.profile.full_name %></h3>
      <!-- TODO: Uncomment after the follow routes are defined
        <a href=<#= follow_path(video.user) %> class="follow-button small has-tip top" data-tooltip aria-haspopup="true" class="has-tip top ic-premio" data-disable-hover='false' tabindex=1 title="Seguir usuário">
        <i class="fa fa-long-arrow-left"></i>
        <i class="fa fa-long-arrow-left"></i>
        <i class="fa fa-long-arrow-left"></i>
        <i class="fa fa-long-arrow-left"></i>
        </a>
      -->
    </div>
    <%= display_location_information(content.user.profile) %>
    <p><%= t('.added_on', date: content.created_at.to_date) %><span class="video-license">BY-NC-SA</span></p>
  </div>
  <div class="right-col">
    <div class="content-icons-group">
      <!-- TODO: Uncomment after video awards are implemented
        <# if video.awarded? %>
          <span data-tooltip aria-haspopup="true" class="has-tip top ic-premio" data-disable-hover='false' tabindex=1 title="<#= t('.awarded')%>"></span>
        <# end %>
      -->
      <% if content.featured? %>
        <span data-tooltip aria-haspopup="true" class="has-tip top ic-destaque" data-disable-hover='false' tabindex=1 title="<%= t('.featured')%>"></span>
      <% end %>
    </div>
    <h3 class="content-views"><%= content.view_count %> <%= t('.views') %></h3>
    <div class="content-rating">
      <% if user_signed_in? %>
        <%= form_tag public_rating_path, id: 'public_rating_form', method: :post, remote: true do %>
        <%= hidden_field_tag 'content_id', content.id %>
        <%# TODO: Public ratings should be available only on public contests %>
        <% cache("content/#{content.id}/average_grade", expires_in: 2.hour) do %>
          <input type="range" min="0" max="5" value="<%= content.average_grade %>" step="0.5" id="content-rating-val" name="grade">
          <div class="rateit" data-rateit-backingfld="#content-rating-val" data-rateit-ispreset="true" data-rateit-starwidth="20" data-rateit-starheight="20"></div>
        <% end %>
        <div>
          <%= button_tag type: 'submit', class: 'evaluate-button' do %>
            <%= t('.evaluate') %>
          <% end %>
          <div id='public_rating_message'></div>
        </div>
      <% end %>
      <% else %>
        <%= t('.needs_to_login_to_evaluate') %>
      <% end %>
    </div>
  </div>

  <div class="columns small-12">
    <!-- Uncomment after the tags backend is complete
      <h3 class="content-tags"><#= t('.contents.show.details.tags') %>
    <# if video.show_tags.empty? %>
      <#= t('.none') %>
    <# else %>
      <#= video.show_tags %>
    <# end %>
    </h3>
    -->
    <h3 class="content-contests"> <%= t('.contests') %>:
      <%= contest_list_for(content) %>
    </h3>
  </div>
</div>

<% content_for :footer do %>
  <%= javascript_include_tag 'contents/public_rating' %>
<% end %>

app/views/contents/_map_button.html.erb
<%= link_to(destination_path, id: 'vjs-map-button-image-destination', className: 'vjs-control-bar', target: '_self') do %>
  <span data-tooltip aria-haspopup="true" class="has-tip left ic-mapa" data-disable-hover="false" tabindex=1 title="<%= t('.caption') %>"></span>
<% end %>

app/views/contents/_map_markers.html.erb
<div class="content-detailed-section">
  <%= hidden_field_tag 'video_link', video_url(video.id) %>
  <input type="hidden" id="latitude-<%= video.id %>" name="latitude" value="<%= video.coordinate.latitude %>">
  <input type="hidden" id="longitude-<%= video.id %>" name="longitude" value="<%= video.coordinate.longitude %>">
  <% if video.featured? %>
    <input type="hidden" name="markerType" value="markerFeatured">
  <% else %>
    <input type="hidden" name="markerType" value="markerNormal">
  <% end %>
  <input type="hidden" id="map_link" value="<%= map_view_path(video.id) %>">
  <input type="hidden" name="map_player_link" value="<%= map_player_path(video.id) %>">
</div>

app/views/contents/_map_player.html.erb
<div class="map-player-box">
  <%= render partial: 'video_player', locals: { content: @content, video: @encoded_video.video } %>
</div>

<%= render partial: 'map_video_details', locals: { video: @content } %>

<input type="hidden" id="share_button_<%=@content.id%>_link" value="<%= share_button_path(@content.id) %>">
<input type="hidden" id="share_box_<%=@content.id%>_link" value="<%= share_box_path(@content.id) %>">

app/views/contents/_map_video_details.html.erb
<div class="content-details">
  <div class="left-col">
    <a href="<%= video_path(video.id) %>"><h2 class="content-title"><%= video.title %></h2></a>
    <!-- TODO: Uncomment after the follow routes are defined
      <div class="inline-grid">
        <h3 class="content-author"><#= t('.by') %> <a href="<#= follow_path(video.user) %>"><#= video.user.full_name %></a></h3>
      </div>
    -->
    <%= display_location_information(video.user.profile) %>
    <p><%= t('contents.content_details.added_on', date: video.created_at.to_date) %><span class="video-license">BY-NC-SA</span></p>
  </div>
  <div class="right-col">
    <div class="content-icons-group">
      <!-- TODO: Uncomment after video awards are implemented
        <# if video.awarded? %>
          <span data-tooltip aria-haspopup="true" class="has-tip top ic-premio" data-disable-hover='false' tabindex=1 title="<#= t('.awarded')%>"></span>
        <# end %>
      -->
      <% if video.featured? %>
        <span data-tooltip aria-haspopup="true" class="has-tip top ic-destaque" data-disable-hover='false' tabindex=1 title="<%= t('contents.content_details.featured')%>"></span>
      <% end %>
    </div>
    <h3 class="content-views"><%= video.view_count %> <%= t('contents.content_details.views') %></h3>
    <div class="content-rating">
      <% if user_signed_in? %>
        <%= form_tag public_rating_path, id: 'public_rating_form', method: :post, remote: true do %>
          <%= hidden_field_tag 'content_id', video.id %>
          <%# TODO: Public ratings should be available only on public contests %>
          <% cache("content/#{video.id}/average_grade", expires_in: 2.hour) do %>
            <input type="range" min="0" max="5" value="<%= video.average_grade %>" step="0.5" id="content-rating-val" name="grade">
            <div class="rateit" data-rateit-backingfld="#content-rating-val" data-rateit-ispreset="true" data-rateit-starwidth="20" data-rateit-starheight="20"></div>
          <% end %>
          <div>
            <%= button_tag type: 'submit', class: 'evaluate-button' do %>
              <%= t('contents.content_details.evaluate') %>
            <% end %>
            <div id='public_rating_message'></div>
          </div>
        <% end %>
      <% else %>
        <%= t('contents.content_details.needs_to_login_to_evaluate') %>
      <% end %>
    </div>
  </div>
</div>

app/views/contents/_share_box.html.erb
<div id="share-box-video-<%= content.id %>" class="vjs-share-box">
  <div class="share-links-group">
    <h3>
      <%= t('.share') %>
    </h3>
    <%= facebook_share(content_url(content), content.title) %>
    <%= twitter_share(content_url(content), content.title) %>
    <%= google_plus_share(content_url(content)) %>
    <%= content_tag(:a, onClick: "toggle_display_element('share-link-modal-video-#{content.id}', 'block')", class: 'fa-stack fa-1x') { icon('link') } %>
    <div class="share-link-modal" id="share-link-modal-video-<%= content.id %>">
      <p><%= t('.share_instructions') %></p>
      <input type="text" value="<%= content_url(content) %>">
      <button class="close-button" aria-label="Close modal" type="button" onClick="document.getElementById('share-link-modal-video-<%= content.id %>').style.display='none';">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
    <button class="close-button" aria-label="Close modal" type="button" onClick="toggle_display_element('share-box-video-' + <%= content.id %>, 'none');">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
</div>

app/views/contents/_share_button.html.erb
<%= content_tag(:a, id: 'vjs-share-button-image-destination', className: 'vjs-control-bar', target: '_self') do %>
  <span data-tooltip aria-haspopup="true" class="has-tip left ic-share" data-disable-hover="false" tabindex=1 title="<%= t('.share') %>" onClick="toggle_display_element('share-box-video-' + <%= id %>, 'block')"></span>
<% end %>

app/views/contents/_video_player.html.erb
<div class="player-box">
  <input type="hidden" id="video-endcap-<%= content.id %>" value="<%= related_contents_path(content.id, format: :json) %>">
  <%# FIXME: Poltergeist server won't recognize the video source if put on a source tag %>
  <video id="video-<%= content.id %>" class="video-js" controls preload="none" data-setup="{}" src="<%= video.url %>" type="video/mp4">
    <p class="vjs-no-js">
    <%= t('.video_js_support_message_html') %>
    </p>
  </video>
</div>

app/views/contents/map_view.html.erb
<%= hidden_field_tag 'video_id', @content.id %>

<main class="map-view-content">
<div id="map-view-section"></div>

  <div class="hide">
    <% @contents.each do |video| %>
      <%= render partial: 'map_markers', locals: { video: video } %>
    <% end %>
  </div>
</main>

<script type="text/javascript" charset="UTF-8">
[
  "https://maps.googleapis.com/maps/api/js?key=<%= "#{GoogleMapsSettings.key}" %>",
  "<%= javascript_path 'contents/map.js' %>"
].forEach(function(src) {
  var script = document.createElement('script');
  script.src = src;
  script.async = false;
  document.head.appendChild(script);
});
</script>

app/views/contents/new.html.erb
<%= render 'form', content: @content %>

app/views/contents/show.html.erb
<main>
  <%= hidden_field_tag 'video_link', content_url(@content.id) %>
  <%= hidden_field_tag 'video_title', @content.title %>
  <div class="content-detailed-section">
    <!-- TODO: include autoplay
  <div class="autoplay-section">
    <div class="autoplay-label"><%= t('.autoplay') %></div>
    <div class="switch tiny">
      <input class="switch-input" id="auto-play" type="checkbox" name="autoplay">
      <label class="switch-paddle" for="auto-play">
        <span class="show-for-sr"><%= t('.autoplay') %></span>
      </label>
    </div>
  </div>
-->

    <div class="content-box">
      <%= render partial: 'video_player', locals: { content: @content, video: @video } %>
    </div>

    <%= render partial: 'content_details', locals: { content: @content } %>
  </div>

  <!-- TODO: implement related contents
<div class="related-content">
  <div class="content-sub-container">
    <div class="inline-grid">
      <ul class="tabs" data-tabs id="example-tabs">
        <li class="tabs-title is-active"><a href="#list-videos-related" aria-selected="true"><%= t('.related_content') %></a></li>
        <li class="tabs-title"><a href="#list-videos-same-author"><%= t('.other_content_from_user')%></a></li>
          TODO: Uncomment and add comments partial after the comment backend
          <# if @video.allow_comments? %>
          <li class="tabs-title"><a href="#comments"><#= t('.comment_this_content') %></a></li>
          <# end %>
      </ul>
    </div>
  </div>

  <div class="tabs-content" data-tabs-content="example-tabs">
    <div class="tabs-panel is-active" id="list-videos-related">
      <div id="list-related">
      </div>

      <p class="see-more">
      <a name="load_related" class="see-more-button"><%= t('see_more') %></a>
      </p>
    </div>

    <div class="tabs-panel" id="list-videos-same-author">
      <div id="list-same">
      </div>

      <p class="see-more">
      <a name="load_more_from_user" class="see-more-button"><%= t('see_more') %></a>
      </p>
    </div>

    TODO: Uncomment and add comments partial after the comment backend
      <#= render partial: 'comments', locals: { video: @video } %>
  </div>
</div>
-->
</main>
<% content_for :footer do %>
  <%= javascript_include_tag 'contents/share_button.js' %>
  <%= javascript_include_tag 'contents/map_button.js' %>
  <%= javascript_include_tag 'contents/related_contents.js' %>
  <%= javascript_tag do %>
    $(document).ready(function() {
      var share_plugin_builder = new ShareButtonPluginBuilder("<%= escape_javascript(render partial: 'share_button', locals: { id: @content.id }) %>", "<%= escape_javascript(render partial: 'share_box', locals: { content: @content }) %>");
      var map_plugin_builder = new MapButtonPluginBuilder("<%= escape_javascript(render partial: 'map_button', locals: { destination_path: map_view_path(@content.id) }) %>");
      video = videojs('video-<%= @content.id %>');
      video.shareButton({ plugin_builder: share_plugin_builder });
      video.mapButton({ plugin_builder: map_plugin_builder });
    })
  <% end %>
<% end %>