config/routes.rb
Rails.application.routes.draw do
  ActiveAdmin.routes(self)
  scope '(:locale)', locale: /en|pt-BR/ do
    devise_for :users, controllers: { confirmations: 'users/confirmations' }
    # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
    resources :profiles, except: [:index]
    resources :contents, only: [:new, :create, :show]
    resources :contests, only: [:show, :index]

    scope format: true, constraints: { format: :json } do
      get '/contents', to: 'contents#index', as: :all_contents
      put '/contents/:id/evaluation', to: 'contents#evaluation', as: :content_evaluation
      get '/videos', to: 'contents#index'
      get '/videos/:id', to: 'contents#video', as: :get_video
      get '/contents/:id/related', to: 'contents#related_contents', as: :related_contents
    end

    scope :contents do
      post '/zencoder_callback', to: 'contents#zencoder_callback', as: :content_zencoder_callback
      get '/:id/map_view', to: 'contents#map_view', as: :map_view
      get '/:id/map_player', to: 'contents#map_player', as: :map_player
      get '/:id/share_button', to: 'contents#share_button', as: :share_button
      get '/:id/share_box', to: 'contents#share_box', as: :share_box
    end

    post '/public_rating', to: 'public_ratings#public_rating', as: :public_rating

    get 'states' => 'profiles#states', as: 'states'

    # static views' routes
    get 'terms_of_use' => 'static_views#terms_of_use', as: 'terms_of_use'
    get 'creative_commons' => 'static_views#creative_commons', as: 'creative_commons'
    get 'sponsorship' => 'static_views#sponsorship', as: 'sponsorship'
    get 'contact_us' => 'static_views#contact_us', as: 'contact_us'
    get 'soundtrack_copyright' => 'static_views#soundtrack_copyright', as: 'soundtrack_copyright'
    get 'faq' => 'static_views#faq', as: 'faq'
    get 'education' => 'static_views#education', as: 'education'
    get 'exhibit_on_your_institution' => 'static_views#exhibit_on_your_institution', as: 'exhibit_on_your_institution'
    get 'about_us' => 'static_views#about_us', as: 'about_us'
    get 'image_copyright' => 'static_views#image_copyright', as: 'image_copyright'
    get 'exhibition_network' => 'static_views#exhibition_network', as: 'exhibition_network'

    root to: 'home#index'
  end
end

app/models/contest.rb
require 'validators/contest_time_validator'

class Contest < ApplicationRecord
  has_many :contest_translations
  has_and_belongs_to_many :contents
  has_and_belongs_to_many :sponsors
  validates :start_date, presence: true
  validates_with ContestTimeValidator, if: 'start_date && end_date'

  scope :started, -> { where('start_date <= :now AND (end_date IS NULL OR end_date >= :ending)', now: Time.zone.now, ending: Time.zone.now - 1.day) }
  scope :finished, -> { where('end_date IS NOT NULL AND end_date <= :now', now: Time.zone.now - 1.day) }

  def name(locale = I18n.locale)
    translation = contest_translations.find_by(locale: locale)
    return I18n.t('missing_contest_translation', field: ContestTranslation.human_attribute_name(__method__), _locale: locale, id: id) if translation.nil?
    translation.name
  end

  def description(locale = I18n.locale)
    translation = contest_translations.find_by(locale: locale)
    return I18n.t('missing_contest_translation', field: ContestTranslation.human_attribute_name(__method__), _locale: locale, id: id) if translation.nil?
    translation.description
  end

  def logo_url(locale = I18n.locale)
    translation = contest_translations.find_by(locale: locale)
    return ActionController::Base.helpers.image_path('logo.jpg') if translation.nil?
    translation.logo.url
  end

  def finished_contents
    contents.evaluated.finished
  end

  def contents_to_show
    finished_contents.order('judge_evaluations.judge_rating DESC', created_at: :desc)
  end

  def started?
    start_date < Time.zone.now
  end

  def finished?
    !end_date.nil? && end_date < Time.zone.now - 1.day
  end

  def ongoing?
    started? && !finished?
  end
end

app/controllers/contests_controller.rb
class ContestsController < ApplicationController
  before_action :set_contest, only: [:show]
  respond_to :html
  respond_to :json, only: [:index]

  # GET /contests/1
  def show
    @sponsors = @contest.sponsors
    @sponsors.each { |sponsor| ViewCounter.create!(viewed_model: Sponsor.to_s, model_id: sponsor.id) }
    @contents_list = Rails.cache.fetch("contest_#{@contest.id}_contents_list", expires_in: 2.hours) { @contest.contents_to_show }
  end

  def index
    @started_contests = Contest.started
    @finished_contests = Contest.finished
    render json: { started_contests: @started_contests, finished_contests: @finished_contests }
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_contest
    @contest = Contest.find(params[:id])
  end
end

app/views/contests/_sponsor.html.erb
<% if sponsor.address.nil? %>
  <%= image_tag(sponsor.logo.url(:thumb)) %>
<% else %>
  <%= link_to sponsor.address do %>
    <%= image_tag(sponsor.logo.url(:thumb)) %>
  <% end %>
<% end %>

app/views/contests/show.html.erb
<% content_for :title, "- #{@contest.name}" if @contest.respond_to?(:name) %>
<main>
<div class="content-detailed-section">
  <div class="columns small-12" style="float: none;">
    <h1><%= @contest.name %></h1>
    <!-- TODO: Add editions to contests
      <h3>edição 9.999</h3>
    -->

    <p>
    <!-- TODO: Add editions to contests
      <a class="button small" data-toggle="panel-other-editions">outras edições</a>
    -->
    <a class="button small" data-toggle="panel-share"><%= t('.share') %></a>
    </p>
    <!-- TODO: Add editions to contests
    <div class="callout" style="display: none;" id="panel-other-editions" data-toggler data-animate="fade-in fade-out" data-closable>
      <button class="close-button" data-close>&times;</button>
      <h4>Outras edições</h4>
      <div id="owl-other-editions" class="owl-carousel">
        {{#repeat 6}}
        {{> list-card-contest}}
        {{/repeat}}
      </div>
    </div>
    -->

    <div class="callout" style="display: none;" id="panel-share" data-toggler data-animate="fade-in fade-out" data-closable>
      <button class="close-button" data-close>&times;</button>
      <h4><%= t('.share') %></h4>
      <div class="share-links-group">
        <%= facebook_share(contest_url(@contest), @contest.name) %>
        <%= twitter_share(contest_url(@contest), @contest.name) %>
        <%= google_plus_share(contest_url(@contest)) %>
        <%= content_tag(:a, 'data-open' => 'share-link-modal', class: 'fa-stack fa-1x') { icon('link') } %>
        <div class="reveal small" id="share-link-modal" data-reveal>
          <p><%= t('contents.share_box.share_instructions') %></p>
          <input type="text" value="<%= contest_url(@contest) %>">
          <button class="close-button" data-close aria-label="Close modal" type="button">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
      </div>
    </div>
  </div>

  <div class="content-box">
    <%= image_tag(@contest.logo_url, alt: @contest.name) %>
  </div>

  <div class="content-details">
    <div class="columns small-12">
      <p class="lead"><%= simple_format(@contest.description, sanitize: true) %></p>

      <% unless @sponsors.empty? %>
        <h3><%= t('.sponsor_section') %></h3>
        <div class="contest-sponsors">
          <%= render partial: 'sponsor', collection: @sponsors, as: :sponsor %>
        </div>
      <% end %>
    </div>
  </div>
</div>

<div class="related-content" id="content-order">
  <div class="columns small-12">
    <h2><%= t('.contest_videos') %></h2>
  </div>
  <!-- TODO: Add these filters to the contest's contents
  <div class="content-sub-container">
    <p class="content-button-group">
    <span><%# "#{t('order_by')}:" %></span>
    <a class="sortby is-active" data-sort="content-featured"><%# t('contents.content_details.featured') %></a>
    <a class="sortby" data-sort="content-upload-date" data-order="desc"><%# t '.recent' %></a>
    <a class="sortby" data-sort="content-type">gifs</a>
    </p>
  </div>
  -->

  <div id="list-videos" class="list">
    <%= render partial: 'shared/list_card_video', collection: @contents_list, as: :video, locals: { scope: '' } %>
  </div>

  <!-- TODO: implement the see more functionality
  <p class="see-more">
  <a class="see-more-button"><%= t 'see_more' %></a>
  </p>
  -->
</div>

<!-- TODO: Add phrase content type
<div class="card-section">
  <div class="columns small-12">
    <h2 class="card-type-title">frases</h2>
  </div>
  <div id="list-phrases">
    {{#repeat 4}}
    {{> list-card-phrase}}
    {{/repeat}}
  </div>

  <p class="see-more">
  <a onclick="loadMore(this, 'list-phrases', 'load-more-phrases');" class="see-more-button">ver mais</a>
  </p>
</div>
-->

<!-- TODO: Add instagram integration
<div class="instagram-section">
  <div class="instagram-header">
    <h2>instagram</h2>
    <p>
    <span class="label">#concurso</span>
    <span class="label">#festivaldominuto</span>
    <span class="label">#hashtag</span>
    <span class="label">#1minuto</span>
    </p>
  </div>
  <div id="owl-instagram" class="owl-carousel">
    {{#repeat 12}}
    <img src="http://lorempixel.com/300/300/cats" alt="">
    {{/repeat}}
  </div>
</div>
-->

<!-- TODO: Add other_contests action
<div class="section">
  <div class="columns small-12">
    <h2>outros concursos</h2>
  </div>
  <div id="list-contests">
    {{#repeat 8}}
    {{> list-card-contest}}
    {{/repeat}}
  </div>
  <p class="see-more">
  <a onclick="loadMore(this, 'list-contests', 'load-more-contests');" class="see-more-button">ver mais</a>
  </p>
  </div>
-->
</main>