config/routes.rb
Rails.application.routes.draw do
  ActiveAdmin.routes(self)
  scope '(:locale)', locale: /en|pt-BR/ do
    devise_for :users, controllers: { confirmations: 'users/confirmations' }
    # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
    resources :profiles, except: [:index]
    resources :contents, only: [:new, :create, :show]
    resources :contests, only: [:show, :index]

    scope format: true, constraints: { format: :json } do
      get '/contents', to: 'contents#index', as: :all_contents
      put '/contents/:id/evaluation', to: 'contents#evaluation', as: :content_evaluation
      get '/videos', to: 'contents#index'
      get '/videos/:id', to: 'contents#video', as: :get_video
      get '/contents/:id/related', to: 'contents#related_contents', as: :related_contents
    end

    scope :contents do
      post '/zencoder_callback', to: 'contents#zencoder_callback', as: :content_zencoder_callback
      get '/:id/map_view', to: 'contents#map_view', as: :map_view
      get '/:id/map_player', to: 'contents#map_player', as: :map_player
      get '/:id/share_button', to: 'contents#share_button', as: :share_button
      get '/:id/share_box', to: 'contents#share_box', as: :share_box
    end

    post '/public_rating', to: 'public_ratings#public_rating', as: :public_rating

    get 'states' => 'profiles#states', as: 'states'

    # static views' routes
    get 'terms_of_use' => 'static_views#terms_of_use', as: 'terms_of_use'
    get 'creative_commons' => 'static_views#creative_commons', as: 'creative_commons'
    get 'sponsorship' => 'static_views#sponsorship', as: 'sponsorship'
    get 'contact_us' => 'static_views#contact_us', as: 'contact_us'
    get 'soundtrack_copyright' => 'static_views#soundtrack_copyright', as: 'soundtrack_copyright'
    get 'faq' => 'static_views#faq', as: 'faq'
    get 'education' => 'static_views#education', as: 'education'
    get 'exhibit_on_your_institution' => 'static_views#exhibit_on_your_institution', as: 'exhibit_on_your_institution'
    get 'about_us' => 'static_views#about_us', as: 'about_us'
    get 'image_copyright' => 'static_views#image_copyright', as: 'image_copyright'
    get 'exhibition_network' => 'static_views#exhibition_network', as: 'exhibition_network'

    root to: 'home#index'
  end
end

app/views/shared/_content_rating.html.erb
<div class="rateit small" data-rateit-value="<%= video.average_grade %>" data-rateit-ispreset="true" data-rateit-readonly="true"></div>

app/views/shared/_list_card_contest.html.erb
<div class="card card-contest">
  <%= link_to contest_path(contest) do %>
    <div class="thumb">
      <%= image_tag contest.logo_url, alt: contest.name %>
      <div class="content-details">
        <h3 class="contest-name"><%= contest.name %></h3>
        <p class="contest-subscription-date">
        <% unless contest.end_date.nil? %>
          <%= t('.contest_subscription_date', date: contest.end_date.strftime("%d/%m/%Y")) %>
        <% end %>
        </p>
      </div>
    </div>
  <% end %>
</div>

app/views/shared/_list_card_video.html.erb
<div class="card card-video">
  <%= render partial: 'shared/list_card_video_base', locals: { video: video, scope: scope } %>
</div>

app/views/shared/_list_card_video_base.html.erb
<div class="thumb content-id" data-id="<%= video.id %>">
  <input type="hidden" class="content-upload-date" data-upload-date="<%= video.created_at %>">
  <input type="hidden" class="content-type" data-type="<%= video.original_medias.last.media.content_type %>">
  <input type="hidden" class="content-featured" data-featured="true<%= video.id %>">
  <a href="<%= content_path(video.id) %>">
    <%= image_tag video.thumbnails.last.url, class: 'thumb-img' %>
  </a>
  <div class="content-details">
    <a href="<%= content_path(video.id) %>">
      <h3 class="content-title"><%= video.title %></h3>
      <p class="content-author"><%= video.user.profile.full_name %></p>
    </a>
    <div class="content-bottom">
      <div class="float-left">
        <p class="content-views"><%= "#{video.view_count} #{t('contents.content_details.views')}" %></p>
        <div class="content-rating">
          <% cache("content/#{video.id}/card_rating", expires_in: 2.hour) do %>
            <%= render partial: 'shared/content_rating', locals: { video: video }  %>
          <% end %>
        </div>
      </div>
      <div class="float-right">
        <div class="content-icons-group">
          <!-- TODO: Add awarded differentiations to contents and reorder the elements: the map icon should come last
          <#% if video.awarded? %>
            <span class="has-tip top ic-premio"></span>
          <#% end  %>
          <#%= link_to map_view_path(video.id) do %>
            <span data-tooltip aria-haspopup="true" class="has-tip top ic-mapa" data-disable-hover='false' tabindex=1 title="<#= t('videos.show.view_on_map') %>"></span>
          <#% end %>
          -->
          <% if video.featured? %>
            <span id="<%= scope %>featured-<%= video.id %>" class="has-tip top ic-destaque"></span>
          <% end  %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/shared/_login_modal.html.erb
<div class="reveal tiny" id="login-modal" data-reveal>
  <h3><%= t('login') %></h3>
  <a class="fb-button" href="#">
    <i class="fa fa-facebook-square"></i>&nbsp; <%= t('login_using_facebook') %>
  </a>
  <hr>
  <p class="lead"><%= t('or_signin_with_form') %></p>
  <form action="" method="get">
    <label><%= t('login') %>:
      <input class="search-box" type="text" placeholder="">
    </label>

    <label><%= t('password') %>:
      <input class="search-box" type="password" placeholder="">
    </label>

    <button type="submit" class="button">
      <%= t('enter') %>
    </button>
  </form>

  <button class="close-button" data-close aria-label="Close modal" type="button">
    <span aria-hidden="true">&times;</span>
  </button>
</div>

app/views/shared/_messages.html.erb
<% flash.each do |key, value| %>
  <div class="<%= flash_to_callout(key) %> callout" data-closable>
    <%= value %>
    <button class="close-button" aria-label="Dismiss alert" type="button" data-close>
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>