config/routes.rb
Rails.application.routes.draw do
  ActiveAdmin.routes(self)
  scope '(:locale)', locale: /en|pt-BR/ do
    devise_for :users, controllers: { confirmations: 'users/confirmations' }
    # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
    resources :profiles, except: [:index]
    resources :contents, only: [:new, :create, :show]
    resources :contests, only: [:show, :index]

    scope format: true, constraints: { format: :json } do
      get '/contents', to: 'contents#index', as: :all_contents
      put '/contents/:id/evaluation', to: 'contents#evaluation', as: :content_evaluation
      get '/videos', to: 'contents#index'
      get '/videos/:id', to: 'contents#video', as: :get_video
      get '/contents/:id/related', to: 'contents#related_contents', as: :related_contents
    end

    scope :contents do
      post '/zencoder_callback', to: 'contents#zencoder_callback', as: :content_zencoder_callback
      get '/:id/map_view', to: 'contents#map_view', as: :map_view
      get '/:id/map_player', to: 'contents#map_player', as: :map_player
      get '/:id/share_button', to: 'contents#share_button', as: :share_button
      get '/:id/share_box', to: 'contents#share_box', as: :share_box
    end

    post '/public_rating', to: 'public_ratings#public_rating', as: :public_rating

    get 'states' => 'profiles#states', as: 'states'

    # static views' routes
    get 'terms_of_use' => 'static_views#terms_of_use', as: 'terms_of_use'
    get 'creative_commons' => 'static_views#creative_commons', as: 'creative_commons'
    get 'sponsorship' => 'static_views#sponsorship', as: 'sponsorship'
    get 'contact_us' => 'static_views#contact_us', as: 'contact_us'
    get 'soundtrack_copyright' => 'static_views#soundtrack_copyright', as: 'soundtrack_copyright'
    get 'faq' => 'static_views#faq', as: 'faq'
    get 'education' => 'static_views#education', as: 'education'
    get 'exhibit_on_your_institution' => 'static_views#exhibit_on_your_institution', as: 'exhibit_on_your_institution'
    get 'about_us' => 'static_views#about_us', as: 'about_us'
    get 'image_copyright' => 'static_views#image_copyright', as: 'image_copyright'
    get 'exhibition_network' => 'static_views#exhibition_network', as: 'exhibition_network'

    root to: 'home#index'
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :configure_devise_parameters, if: :devise_controller?
  before_action :set_locale

  rescue_from ActiveRecord::RecordNotFound, with: :render_404

  protected

  # We don't have a way to test this unless we have the Devise controllers among our code.
  # Since creating the controllers looks wronger than not testing this two
  # lines. I think we can live without 100% of coverage
  # :nocov:
  def configure_devise_parameters
    devise_parameter_sanitizer.permit(:sign_up) do |user_params|
      user_params.permit(:email, :email_confirmation, :password, :password_confirmation)
    end
  end
  # :nocov:

  def set_locale
    I18n.locale = (
      params[:locale] ||
      http_accept_language.compatible_language_from(I18n.available_locales) ||
      I18n.default_locale
    )
  end

  def default_url_options(options = {})
    { locale: I18n.locale }.merge options
  end

  def authenticate_admin_user!
    if current_user.nil? || !current_user.admin
      flash[:error] = I18n.t(:unauthenticated, scope: [:devise, :failure])
      redirect_to root_path
    end
  end

  def current_admin_user
    return nil if current_user.nil? || !current_user.admin?
    current_user
  end

  private

  def render_404
    render file: File.join(Rails.root, 'public', '404.html'), layout: false, status: 404
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def i18n_logo
    "logo-#{I18n.locale}.png"
  end

  def i18n_top_banner
    "top-banner-#{I18n.locale}.png"
  end

  def flash_to_callout(key)
    key = 'success' if key == 'notice'
    key
  end

  def sponsor_banner
    image_tag "sponsor-banner-#{I18n.locale}.png"
  end
end

app/views/application/_footer.html.erb
<footer>
  <ul>
    <li><%= t('recommend') %></li>
    <li><%= link_to t('copyright'), t('copyright_url'), target: '_blank' %></li>
    <li><%= link_to t('public_domain'), t('public_domain_url'), target: '_blank' %></li>
    <li><%= link_to t('creative_commons'), creative_commons_path, :data => { :colorbox => true, :colorbox_height => '80%', :colorbox_width => '80%' } %></li>
    <li><%= link_to t('soundtrack_copyright'), soundtrack_copyright_path, :data => { :colorbox => true, :colorbox_height => '55%', :colorbox_width => '80%' } %></li>
    <li><%= link_to t('image_copyright'), image_copyright_path, :data => { :colorbox => true, :colorbox_height => '55%', :colorbox_width => '80%' } %></li>
    <li><%= link_to t('faq'), faq_path, :data => { :colorbox => true, :colorbox_height => '80%', :colorbox_width => '80%' } %></li>
  </ul>

  <ul>
    <li><%= t('know_more') %></li>
    <li><%= link_to t('exhibition_network'), exhibition_network_path, :data => { :colorbox => true, :colorbox_height => '80%', :colorbox_width => '80%' } %></li>
    <li><%= link_to t('sourcecode'), 'https://gitlab.com/minuto/media_choice', target: '_blank' %></li>
  </ul>

  <ul>
    <li><%= t('minute') %></li>
    <li><%= link_to t('about'), about_us_path, :data => { :colorbox => true, :colorbox_height => '80%', :colorbox_width => '80%' } %></li>
    <li><%= link_to t('show'), exhibit_on_your_institution_path, :data => { :colorbox => true, :colorbox_height => '50%', :colorbox_width => '80%' } %></li>
    <li><%= link_to t('terms'), terms_of_use_path, :data => { :colorbox => true, :colorbox_height => '80%', :colorbox_width => '80%' } %></li>
    <li><%= link_to t('sponsorship'), sponsorship_path, :data => { :colorbox => true, :colorbox_height => '40%', :colorbox_width => '80%' } %></li>
    <li><%= link_to t('contact'), contact_us_path, :data => { :colorbox => true, :colorbox_height => '35%', :colorbox_width => '80%' } %></li>
    <li><%= link_to t('education'), education_path, :data => { :colorbox => true, :colorbox_height => '60%', :colorbox_width => '80%' } %></li>
  </ul>
  <!-- If you want to use Quick Access, uncomment here and see _footer.scss
    <div>
      <h3><%= t('quick') %></h3>
      <select>
        <option value="videos"><%= t('videos') %></option>
        <option value="enviar conteudo"><%= t('submit') %></option>
        <option value="concursos"><%= t('contests') %></option>
        <option value="noticias"><%= t('news') %></option>
        <option value="ajuda"><%= t('help') %></option>
        <option value="imprensa"><%= t('press') %></option>
      </select>
    </div>
  -->
</footer>

app/views/application/_navbar.html.erb
<header class="general-header">
  <div class="top-bar">
    <div class="top-bar-title">
      <div class="logo">
        <%= link_to(image_tag(i18n_logo, class: 'img-responsive'), root_path) %>
      </div>
      <span data-responsive-toggle="responsive-menu" data-hide-for="large">
        <span class="menu-icon dark" data-toggle></span>
      </span>
    </div>
    <div id="responsive-menu">
      <div class="top-bar-right">
        <ul class="dropdown menu primary-menu" data-dropdown-menu>
          <li>
            <%= link_to(t('upload_content'), new_content_path, class: 'featured-link') %>
          </li>
          <!-- This page is not ready yet
          <li>
            <%= link_to(Contest.model_name.human(count: 2), '#') %>
          </li>
          -->
          <% if user_signed_in? %>
            <li>
              <a id='my-account' href="#">
                <%= t("account.my") %> <span class="caret"></span>
              </a>
              <ul class="menu">
                <!-- TODO: implement user edition
                <li>
                  <%= link_to t('account.edit'), edit_user_registration_path(current_user.id) %>
                </li>
                -->
                <% if current_user.profile.present? %>
                  <li>
                    <%= link_to t('profile_links.edit'), edit_profile_path(current_user.profile) %>
                  </li>
                  <li>
                    <%= link_to t('account.my_page'), profile_path(current_user.profile) %>
                  </li>
                <% else %>
                  <li>
                    <%= link_to t('profile_links.new'), new_profile_path %>
                  </li>
                <% end %>
                <!-- TODO: this would be a route to my_friends_path(current_user)
                <li>
                  <%= link_to t('account.friends'), '#' %>
                </li>
                -->
                <li>
                  <%= link_to t('account.signout'), destroy_user_session_path, method: :delete %>
                </li>
              </ul>
            </li>
            <li>
              <% if current_user.admin? %>
              <%= link_to t('control_panel'), admin_root_path %>
              <% end %>
            </li>
          <% else %>
            <li>
              <%= link_to t('account.signup'), new_user_registration_path %>
            </li>
            <li>
              <a id="login_link" data-open="login-modal"><%= t('login') %></a>
            </li>
          <% end %>
          <li>
            <a class="language-selector" href="#"><%= t('home.language') %></a>
            <ul class="menu">
              <% I18n.available_locales.each do |locale| %>
                <li>
                  <%= link_to("/#{locale}", data: { no_turbolink: true }, class: locale) do %>
                    <%= image_tag("#{locale}-icon.png") %><%= locale == :en ? 'english' : 'português' %>
                  <% end %>
                </li>
              <% end %>
            </ul>
          </li>
        </ul>
        <ul class="menu secondary-menu">
          <!-- TODO: implement searches
          <li>
            <form action="search.html" method="get">
              <input class="search-box" type="search" placeholder="<%= t('looking_for') %>">
              <button type="submit" class="search-button">
                <i class="fa fa-search"></i>
              </button>
            </form>
          </li>
          -->
          <li>
            <div class="social-links-group">
              <%= link_to 'http://facebook.com/festivaldominuto', target: '_blank' do %>
                <i class="fa fa-facebook"></i>
              <% end %>
              <%= link_to 'http://twitter.com/festivaldominuto', target: '_blank' do %>
                <i class="fa fa-twitter"></i>
              <% end %>
              <%= link_to 'http://vimeo.com/oneminutefestivalbr', target: '_blank' do %>
                <i class="fa fa-vimeo"></i>
              <% end %>
              <%= link_to 'http://youtube.com/user/festivaldominuto', target: '_blank' do %>
                <i class="fa fa-youtube-play"></i>
              <% end %>
            </div>
          </li>
        </ul>
      </div>
    </div>
  </div>
</header>
<% unless user_signed_in? %>
  <div class="reveal tiny" id="login-modal" data-reveal>
    <h3><%= t('home.do_login') %></h3>
    <!-- TODO: implement facebook integration
    <a class="fb-button" href="#">
      <i class="fa fa-facebook-square"></i>&nbsp; <%= t('home.login_with_facebook') %>
    </a>
    <hr>
    <p class="lead"><%= t('complete_form') %>:</p>
    -->

    <%= form_for(:user, url: session_path(:user)) do |f| %>
      <div class="field">
        <%= f.label t('email') %><br />
        <%= f.email_field :email, autofocus: true, class: 'search-box' %>
      </div>

      <div class="field">
        <%= f.label t('password') %><br />
        <%= f.password_field :password, autocomplete: "off", class: 'search-box' %>
      </div>

      <div class="field">
        <%= f.check_box :remember_me %>
        <%= f.label t('remember_me') %>
      </div>

      <%= f.submit I18n.t('enter'), class: 'button' %>
    <% end %>

    <button class="close-button" data-close aria-label="Close modal" type="button">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>